# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: DTS
    url: '/dts'
    weight: 10
  - name: Get Involved
    url: '/get-involved'
    weight: 20
  - name: About
    identifier: about
    weight: 30
  - name: Vision
    parent: about
    url: '/vision'
    weight: 20
  - name: Blog
    parent: about
    url: 'https://www.medium.com/ywamsendai'
    weight: 30
  - name: Contact
    parent: about
    url: '#contact'
    weight: 40
  - name: Donate
    url: '/donate'
    weight: 40
  - name: Online Handbook
    url: 'https://docs.ywamsendai.org'
    weight: 50
